services:
  - type: web
    name: mise
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEO4J_URI
        sync: bolt+s://db-9992310b.databases.cognodb.com
      - key: NEO4J_USER
        value: cognodb
      - key: NEO4J_PASSWORD
        sync: 654ea26490c082443181abec3b96bdfa
