export const restaurant = {
  id: "hearth-tide",
  name: "Hearth & Tide",
  city: "Portland, Maine",
  note: "42-seat coastal kitchen. One pass, six stations, shared fryer oil.",
};

export const allergens = [
  { id: "gluten", name: "Gluten (cereals)", code: "A", icon: "wheat" },
  { id: "crustaceans", name: "Crustaceans", code: "B", icon: "shrimp" },
  { id: "eggs", name: "Eggs", code: "C", icon: "egg" },
  { id: "fish", name: "Fish", code: "D", icon: "fish" },
  { id: "peanuts", name: "Peanuts", code: "E", icon: "peanut" },
  { id: "soy", name: "Soy", code: "F", icon: "bean" },
  { id: "milk", name: "Milk", code: "G", icon: "milk" },
  { id: "nuts", name: "Tree nuts", code: "H", icon: "nut" },
  { id: "celery", name: "Celery", code: "I", icon: "celery" },
  { id: "mustard", name: "Mustard", code: "J", icon: "mustard" },
  { id: "sesame", name: "Sesame", code: "K", icon: "sesame" },
  { id: "sulphites", name: "Sulphites", code: "L", icon: "wine" },
  { id: "lupin", name: "Lupin", code: "M", icon: "lupin" },
  { id: "molluscs", name: "Molluscs", code: "N", icon: "shell" },
];

export const stations = [
  { id: "garde", name: "Garde manger", kind: "cold" },
  { id: "grill", name: "Grill / flat-top", kind: "hot" },
  { id: "saute", name: "Sauté", kind: "hot" },
  { id: "fryer", name: "Fryer", kind: "hot" },
  { id: "pasta", name: "Pasta", kind: "hot" },
  { id: "pastry", name: "Pastry", kind: "pastry" },
  { id: "bread", name: "Bread", kind: "pastry" },
  { id: "pass", name: "The pass", kind: "expo" },
];

export const equipment = [
  { id: "flattop", name: "Flat-top grill", kind: "grill", note: "Fish and steak share this steel." },
  { id: "saute-range", name: "Sauté range", kind: "range", note: "One set of pans, six burners." },
  { id: "fryer-a", name: "Fryer A", kind: "fryer", note: "Shared oil — calamari, fries, fried chicken." },
  { id: "mixer", name: "Hobart mixer", kind: "mixer", note: "Bread dough and cake batter." },
  { id: "wood-oven", name: "Wood oven", kind: "oven", note: "Bread and finishing." },
  { id: "pasta-kettle", name: "Pasta kettle", kind: "kettle", note: "Water is changed twice a service." },
  { id: "fish-boards", name: "Fish boards", kind: "board", note: "Dedicated, but washed in the same pit." },
  { id: "pastry-bench", name: "Pastry bench", kind: "bench", note: "Flour dust travels." },
  { id: "cold-well", name: "Cold well", kind: "cold", note: "Oysters and dairy share the drawer." },
];

export const stationUses = [
  { station: "garde", equipment: "cold-well" },
  { station: "garde", equipment: "fish-boards" },
  { station: "grill", equipment: "flattop" },
  { station: "saute", equipment: "saute-range" },
  { station: "fryer", equipment: "fryer-a" },
  { station: "pasta", equipment: "pasta-kettle" },
  { station: "pasta", equipment: "saute-range" },
  { station: "pastry", equipment: "mixer" },
  { station: "pastry", equipment: "pastry-bench" },
  { station: "bread", equipment: "mixer" },
  { station: "bread", equipment: "wood-oven" },
  { station: "pass", equipment: "flattop" },
];

export const staff = [
  { id: "mara", name: "Mara Ellison", role: "Chef de cuisine" },
  { id: "jun", name: "Jun Park", role: "Pastry" },
  { id: "theo", name: "Theo Nash", role: "Grill" },
  { id: "samira", name: "Samira Cole", role: "Fryer" },
  { id: "eli", name: "Eli Voss", role: "Garde manger" },
  { id: "nina", name: "Nina Ortiz", role: "Pasta" },
];

export const staffRuns = [
  { staff: "mara", station: "pass" },
  { staff: "jun", station: "pastry" },
  { staff: "jun", station: "bread" },
  { staff: "theo", station: "grill" },
  { staff: "samira", station: "fryer" },
  { staff: "eli", station: "garde" },
  { staff: "nina", station: "pasta" },
  { staff: "nina", station: "saute" },
];

export const suppliers = [
  { id: "atlantic", name: "Atlantic Shellfish Co.", city: "Stonington", country: "USA", riskLevel: "high", goods: "oysters, clams, lobster, calamari" },
  { id: "pacific", name: "Pacific Catch", city: "Portland", country: "USA", riskLevel: "medium", goods: "halibut, scallops" },
  { id: "valley", name: "Valley Dairy", city: "Turner", country: "USA", riskLevel: "watch", goods: "cream, ricotta, butter, cream cheese" },
  { id: "golden", name: "Golden Grain Mill", city: "Waterville", country: "USA", riskLevel: "low", goods: "flour, pasta" },
  { id: "forest", name: "Forest Mushroom Co.", city: "Bethel", country: "USA", riskLevel: "low", goods: "mushrooms" },
  { id: "orchard", name: "Orchard Hill", city: "Sebago", country: "USA", riskLevel: "low", goods: "beets, greens, herbs" },
  { id: "hearth-beef", name: "Hearth Cattle", city: "Damariscotta", country: "USA", riskLevel: "low", goods: "dry-aged beef, duck" },
  { id: "northnut", name: "Northnut Orchards", city: "Vermont", country: "USA", riskLevel: "medium", goods: "walnuts, almonds" },
];

export const ingredients: {
  id: string;
  name: string;
  kind: string;
  allergens: string[];
  supplier: string;
}[] = [
  { id: "oyster", name: "East Coast oysters", kind: "seafood", allergens: ["molluscs"], supplier: "atlantic" },
  { id: "clam", name: "Steamers / chowder clams", kind: "seafood", allergens: ["molluscs"], supplier: "atlantic" },
  { id: "lobster", name: "Maine lobster", kind: "seafood", allergens: ["crustaceans"], supplier: "atlantic" },
  { id: "calamari", name: "Calamari", kind: "seafood", allergens: ["molluscs"], supplier: "atlantic" },
  { id: "scallop", name: "Day-boat scallops", kind: "seafood", allergens: ["molluscs"], supplier: "pacific" },
  { id: "halibut", name: "Halibut", kind: "seafood", allergens: ["fish"], supplier: "pacific" },
  { id: "anchovy", name: "Salted anchovy", kind: "seafood", allergens: ["fish"], supplier: "pacific" },
  { id: "flour", name: "Bread flour", kind: "dry", allergens: ["gluten"], supplier: "golden" },
  { id: "pasta", name: "Fresh linguine", kind: "dry", allergens: ["gluten", "eggs"], supplier: "golden" },
  { id: "brioche", name: "Brioche roll", kind: "dry", allergens: ["gluten", "eggs", "milk"], supplier: "golden" },
  { id: "rye", name: "Rye toast", kind: "dry", allergens: ["gluten"], supplier: "golden" },
  { id: "crouton", name: "Sourdough croutons", kind: "dry", allergens: ["gluten"], supplier: "golden" },
  { id: "cream", name: "Heavy cream", kind: "dairy", allergens: ["milk"], supplier: "valley" },
  { id: "ricotta", name: "Whipped ricotta", kind: "dairy", allergens: ["milk"], supplier: "valley" },
  { id: "butter", name: "Cultured butter", kind: "dairy", allergens: ["milk"], supplier: "valley" },
  { id: "cream-cheese", name: "Cream cheese", kind: "dairy", allergens: ["milk"], supplier: "valley" },
  { id: "parmesan", name: "Parmesan", kind: "dairy", allergens: ["milk"], supplier: "valley" },
  { id: "goat", name: "Goat cheese", kind: "dairy", allergens: ["milk"], supplier: "valley" },
  { id: "gelato", name: "Vanilla gelato", kind: "dairy", allergens: ["milk", "eggs"], supplier: "valley" },
  { id: "egg", name: "Eggs", kind: "dairy", allergens: ["eggs"], supplier: "valley" },
  { id: "buttermilk", name: "Buttermilk", kind: "dairy", allergens: ["milk"], supplier: "valley" },
  { id: "mayo", name: "House mayonnaise", kind: "prep", allergens: ["eggs"], supplier: "valley" },
  { id: "mushroom", name: "Forest mushrooms", kind: "produce", allergens: [], supplier: "forest" },
  { id: "beet", name: "Roasted beets", kind: "produce", allergens: [], supplier: "orchard" },
  { id: "gem", name: "Little gem lettuce", kind: "produce", allergens: [], supplier: "orchard" },
  { id: "herb", name: "Parsley / salsa verde herbs", kind: "produce", allergens: [], supplier: "orchard" },
  { id: "potato", name: "Kennebec potatoes", kind: "produce", allergens: [], supplier: "orchard" },
  { id: "celery", name: "Celery", kind: "produce", allergens: ["celery"], supplier: "orchard" },
  { id: "chili", name: "Calabrian chili", kind: "dry", allergens: [], supplier: "orchard" },
  { id: "honey", name: "Hot honey", kind: "dry", allergens: [], supplier: "orchard" },
  { id: "cherry", name: "Sour cherries", kind: "produce", allergens: [], supplier: "orchard" },
  { id: "lemon", name: "Lemon", kind: "produce", allergens: [], supplier: "orchard" },
  { id: "wine", name: "White wine", kind: "dry", allergens: ["sulphites"], supplier: "orchard" },
  { id: "beef", name: "Dry-aged ribeye", kind: "protein", allergens: [], supplier: "hearth-beef" },
  { id: "duck", name: "Duck legs", kind: "protein", allergens: [], supplier: "hearth-beef" },
  { id: "chicken", name: "Heritage chicken", kind: "protein", allergens: [], supplier: "hearth-beef" },
  { id: "walnut", name: "Walnuts", kind: "dry", allergens: ["nuts"], supplier: "northnut" },
  { id: "almond", name: "Almond flour", kind: "dry", allergens: ["nuts"], supplier: "northnut" },
  { id: "chocolate", name: "70% chocolate", kind: "dry", allergens: ["soy"], supplier: "golden" },
  { id: "espresso", name: "Espresso", kind: "dry", allergens: [], supplier: "golden" },
  { id: "rice", name: "Carnaroli rice", kind: "dry", allergens: [], supplier: "golden" },
  { id: "olive-oil", name: "Olive oil", kind: "dry", allergens: [], supplier: "orchard" },
  { id: "pickle", name: "House pickles", kind: "prep", allergens: ["mustard"], supplier: "orchard" },
  { id: "sesame", name: "Toasted sesame", kind: "dry", allergens: ["sesame"], supplier: "golden" },
  { id: "peanut-oil", name: "Peanut oil (backup fryer)", kind: "dry", allergens: ["peanuts"], supplier: "golden" },
];

export const dishes = [
  {
    id: "oysters",
    name: "Oyster plateau",
    course: "cold",
    price: 28,
    vegetarian: false,
    sort: 1,
    description: "A dozen East Coast oysters, mignonette, lemon, rye toast.",
    ingredients: ["oyster", "lemon", "rye", "wine"],
    stations: ["garde", "bread"],
  },
  {
    id: "caesar",
    name: "Little gem Caesar",
    course: "cold",
    price: 16,
    vegetarian: false,
    sort: 2,
    description: "Anchovy, parmesan, egg yolk dressing, sourdough croutons.",
    ingredients: ["gem", "anchovy", "parmesan", "egg", "crouton"],
    stations: ["garde", "bread"],
  },
  {
    id: "ricotta",
    name: "Whipped ricotta",
    course: "cold",
    price: 15,
    vegetarian: true,
    sort: 3,
    description: "Valley ricotta, chili oil, honey, warm sourdough.",
    ingredients: ["ricotta", "chili", "honey", "flour"],
    stations: ["garde", "bread"],
  },
  {
    id: "beets",
    name: "Beet & goat cheese",
    course: "cold",
    price: 16,
    vegetarian: true,
    sort: 4,
    description: "Roasted beets, goat cheese, walnuts, sherry vinaigrette.",
    ingredients: ["beet", "goat", "walnut", "herb"],
    stations: ["garde"],
  },
  {
    id: "chowder",
    name: "Clam chowder",
    course: "hot",
    price: 18,
    vegetarian: false,
    sort: 5,
    description: "Steamers, potato, celery, cream. Served with rye.",
    ingredients: ["clam", "potato", "celery", "cream", "rye"],
    stations: ["saute", "bread"],
  },
  {
    id: "scallops",
    name: "Seared scallops",
    course: "hot",
    price: 34,
    vegetarian: false,
    sort: 6,
    description: "Day-boat scallops, brown butter, cauliflower.",
    ingredients: ["scallop", "butter"],
    stations: ["saute"],
  },
  {
    id: "halibut",
    name: "Market fish",
    course: "hot",
    price: 36,
    vegetarian: false,
    sort: 7,
    description: "Halibut, salsa verde, crushed potato. Finished on the flat-top.",
    ingredients: ["halibut", "herb", "potato", "anchovy", "olive-oil"],
    stations: ["grill"],
  },
  {
    id: "duck",
    name: "Duck confit",
    course: "hot",
    price: 32,
    vegetarian: false,
    sort: 8,
    description: "Duck leg, sour cherry, polenta.",
    ingredients: ["duck", "cherry", "butter"],
    stations: ["saute"],
  },
  {
    id: "ribeye",
    name: "Dry-aged ribeye",
    course: "hot",
    price: 58,
    vegetarian: false,
    sort: 9,
    description: "Hearth Cattle ribeye, cultured butter, hand-cut fries.",
    ingredients: ["beef", "butter", "potato"],
    stations: ["grill", "fryer"],
  },
  {
    id: "risotto",
    name: "Mushroom risotto",
    course: "hot",
    price: 26,
    vegetarian: true,
    sort: 10,
    description: "Carnaroli, forest mushrooms, parmesan.",
    ingredients: ["rice", "mushroom", "parmesan", "butter"],
    stations: ["saute"],
  },
  {
    id: "lobster-roll",
    name: "Lobster roll",
    course: "hot",
    price: 32,
    vegetarian: false,
    sort: 11,
    description: "Warm buttered lobster, celery, brioche.",
    ingredients: ["lobster", "mayo", "celery", "brioche", "butter"],
    stations: ["garde", "bread"],
  },
  {
    id: "fried-chicken",
    name: "Fried chicken",
    course: "hot",
    price: 24,
    vegetarian: false,
    sort: 12,
    description: "Buttermilk brine, hot honey, house pickles. Same fryer as calamari.",
    ingredients: ["chicken", "buttermilk", "flour", "honey", "pickle"],
    stations: ["fryer"],
  },
  {
    id: "calamari-dish",
    name: "Fried calamari",
    course: "hot",
    price: 19,
    vegetarian: false,
    sort: 13,
    description: "Salt, lemon, chili. Lives in Fryer A all service.",
    ingredients: ["calamari", "flour", "lemon", "chili"],
    stations: ["fryer"],
  },
  {
    id: "vongole",
    name: "Linguine alle vongole",
    course: "hot",
    price: 29,
    vegetarian: false,
    sort: 14,
    description: "Clams, garlic, chili, white wine.",
    ingredients: ["pasta", "clam", "chili", "wine", "olive-oil"],
    stations: ["pasta"],
  },
  {
    id: "fries",
    name: "Hand-cut fries",
    course: "hot",
    price: 9,
    vegetarian: true,
    sort: 15,
    description: "Kennebecs. Looks vegetarian. Shares oil with calamari.",
    ingredients: ["potato"],
    stations: ["fryer"],
  },
  {
    id: "pot-de-creme",
    name: "Chocolate pot de crème",
    course: "pastry",
    price: 12,
    vegetarian: true,
    sort: 16,
    description: "70% chocolate, cream, egg. Sesame brittle.",
    ingredients: ["chocolate", "cream", "egg", "sesame"],
    stations: ["pastry"],
  },
  {
    id: "olive-cake",
    name: "Citrus olive oil cake",
    course: "pastry",
    price: 12,
    vegetarian: true,
    sort: 17,
    description: "Almond flour, olive oil, citrus. Mixed in the Hobart.",
    ingredients: ["almond", "flour", "egg", "olive-oil", "lemon"],
    stations: ["pastry"],
  },
  {
    id: "affogato",
    name: "Affogato",
    course: "pastry",
    price: 11,
    vegetarian: true,
    sort: 18,
    description: "Vanilla gelato, espresso.",
    ingredients: ["gelato", "espresso"],
    stations: ["pastry"],
  },
  {
    id: "cheesecake",
    name: "Burnt Basque cheesecake",
    course: "pastry",
    price: 13,
    vegetarian: true,
    sort: 19,
    description: "Valley cream cheese, burnt top. Tonight's problem child.",
    ingredients: ["cream-cheese", "egg", "cream"],
    stations: ["pastry"],
  },
  {
    id: "sourdough",
    name: "House sourdough",
    course: "bread",
    price: 7,
    vegetarian: true,
    sort: 20,
    description: "Wood-oven loaf, cultured butter.",
    ingredients: ["flour", "butter"],
    stations: ["bread"],
  },
];

export const lots = [
  { id: "lot-oys", code: "AS-OY-118", ingredient: "oyster", supplier: "atlantic", receivedOn: "2026-08-16", status: "ok", note: "Cold well, same drawer as dairy." },
  { id: "lot-clam", code: "AS-CL-204", ingredient: "clam", supplier: "atlantic", receivedOn: "2026-08-16", status: "ok", note: null },
  { id: "lot-lob", code: "AS-LB-091", ingredient: "lobster", supplier: "atlantic", receivedOn: "2026-08-15", status: "ok", note: null },
  { id: "lot-cal", code: "AS-SQ-055", ingredient: "calamari", supplier: "atlantic", receivedOn: "2026-08-16", status: "ok", note: "In the fryer all night." },
  { id: "lot-hal", code: "PC-HA-330", ingredient: "halibut", supplier: "pacific", receivedOn: "2026-08-17", status: "ok", note: "On the flat-top with the ribeye." },
  { id: "lot-sca", code: "PC-SC-212", ingredient: "scallop", supplier: "pacific", receivedOn: "2026-08-17", status: "ok", note: null },
  { id: "lot-cream", code: "VD-CR-880", ingredient: "cream", supplier: "valley", receivedOn: "2026-08-14", status: "ok", note: null },
  { id: "lot-cc", code: "VD-CC-4412", ingredient: "cream-cheese", supplier: "valley", receivedOn: "2026-08-12", status: "recalled", note: "Listeria watch — Valley Dairy voluntary recall." },
  { id: "lot-but", code: "VD-BT-119", ingredient: "butter", supplier: "valley", receivedOn: "2026-08-15", status: "watch", note: "Same plant as the recalled cream cheese." },
  { id: "lot-ric", code: "VD-RC-077", ingredient: "ricotta", supplier: "valley", receivedOn: "2026-08-16", status: "ok", note: null },
  { id: "lot-fl", code: "GG-FL-500", ingredient: "flour", supplier: "golden", receivedOn: "2026-08-10", status: "ok", note: "Mixer + fryer dredge." },
  { id: "lot-alm", code: "NN-AL-018", ingredient: "almond", supplier: "northnut", receivedOn: "2026-08-11", status: "ok", note: "Pastry bench and mixer." },
  { id: "lot-wal", code: "NN-WA-022", ingredient: "walnut", supplier: "northnut", receivedOn: "2026-08-11", status: "ok", note: null },
  { id: "lot-beef", code: "HC-RB-044", ingredient: "beef", supplier: "hearth-beef", receivedOn: "2026-08-15", status: "ok", note: null },
  { id: "lot-chk", code: "HC-CH-090", ingredient: "chicken", supplier: "hearth-beef", receivedOn: "2026-08-16", status: "ok", note: "Dredged then Fryer A." },
  { id: "lot-msh", code: "FM-MS-301", ingredient: "mushroom", supplier: "forest", receivedOn: "2026-08-17", status: "ok", note: null },
];

export const lotTouched = [
  { lot: "lot-oys", equipment: "cold-well" },
  { lot: "lot-oys", equipment: "fish-boards" },
  { lot: "lot-clam", equipment: "saute-range" },
  { lot: "lot-cal", equipment: "fryer-a" },
  { lot: "lot-hal", equipment: "flattop" },
  { lot: "lot-hal", equipment: "fish-boards" },
  { lot: "lot-sca", equipment: "saute-range" },
  { lot: "lot-cc", equipment: "mixer" },
  { lot: "lot-cc", equipment: "pastry-bench" },
  { lot: "lot-but", equipment: "saute-range" },
  { lot: "lot-but", equipment: "flattop" },
  { lot: "lot-fl", equipment: "mixer" },
  { lot: "lot-fl", equipment: "fryer-a" },
  { lot: "lot-alm", equipment: "mixer" },
  { lot: "lot-alm", equipment: "pastry-bench" },
  { lot: "lot-chk", equipment: "fryer-a" },
  { lot: "lot-beef", equipment: "flattop" },
  { lot: "lot-lob", equipment: "cold-well" },
];
